### ISSUE TITLE
Update build.gradle for Dependency Management

### ISSUE THREAD

**Issue by Json604** [ionicappdevelopment/basic-app#2]
**Description:**
The build.gradle file requires updates to enhance dependency management and ensure compatibility with the latest standards. The following changes are proposed:

**Changes:**
1. Replace deprecated jcenter():
The jcenter() repository has been deprecated since February 2021 and is now read-only. It is recommended to replace 
it with mavenCentral().

2. Upgrade Android Gradle Plugin:
The current Android Gradle Plugin is set to version 3.6.1, which is outdated. Upgrading to version 7.0.4 will improve build performance and ensure compatibility with the latest Android SDKs.

3.Upgrade Google Services Plugin:
The Google Services Plugin is currently at version 4.3.3. Updating it to version 4.3.15 will enhance support for Firebase and other Google services.

**Steps to Reproduce:**
1. Open the build.gradle file.
2. Observe that jcenter() is included in the repositories section.
3. Check the versions of the Android Gradle Plugin and Google Services Plugin.

**Suggested Fix:**
1.Replace jcenter() with mavenCentral() in both the buildscript and allprojects sections of the build.gradle file.
2. Update the Android Gradle Plugin version to 7.0.4.
3. Update the Google Services Plugin version to 4.3.15.

**File(s) Affected:**
build.gradle

**Comment by sunny7899** [comment]
Go ahead @Kartikey060105
