### ISSUE TITLE
Missing CONTRIBUTING.md File

### ISSUE THREAD

**Issue by anshgautam-github** [ionicappdevelopment/basic-app#5]
I noticed that the repository does not contain a CONTRIBUTING.md file, which typically provides guidelines for contributing to the project. This file is essential for outlining how contributors can get involved, the coding standards to follow, and the process for submitting issues or pull requests.

Kindly assign this issue to me under hacktoberfest.

**Comment by sunny7899** [comment]
great Go ahead @anshgautam-github
